// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/code/service.proto

package code

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	protobuf "oojob/protobuf"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ContestSlug          string   `protobuf:"bytes,2,opt,name=contest_slug,json=contestSlug,proto3" json:"contest_slug,omitempty"`
	Language             string   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	PlaylistSlug         string   `protobuf:"bytes,4,opt,name=playlist_slug,json=playlistSlug,proto3" json:"playlist_slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeRequest) Reset()         { *m = CodeRequest{} }
func (m *CodeRequest) String() string { return proto.CompactTextString(m) }
func (*CodeRequest) ProtoMessage()    {}
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291bbfa232056f92, []int{0}
}

func (m *CodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeRequest.Unmarshal(m, b)
}
func (m *CodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeRequest.Marshal(b, m, deterministic)
}
func (m *CodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRequest.Merge(m, src)
}
func (m *CodeRequest) XXX_Size() int {
	return xxx_messageInfo_CodeRequest.Size(m)
}
func (m *CodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRequest proto.InternalMessageInfo

func (m *CodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CodeRequest) GetContestSlug() string {
	if m != nil {
		return m.ContestSlug
	}
	return ""
}

func (m *CodeRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CodeRequest) GetPlaylistSlug() string {
	if m != nil {
		return m.PlaylistSlug
	}
	return ""
}

type CodeResponse struct {
	ChallengeId          string   `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ChallengeSlug        string   `protobuf:"bytes,2,opt,name=challenge_slug,json=challengeSlug,proto3" json:"challenge_slug,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CodecheckerHash      string   `protobuf:"bytes,4,opt,name=codechecker_hash,json=codecheckerHash,proto3" json:"codechecker_hash,omitempty"`
	Company              string   `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	CompileMessage       string   `protobuf:"bytes,6,opt,name=compile_message,json=compileMessage,proto3" json:"compile_message,omitempty"`
	CompileStatus        bool     `protobuf:"varint,7,opt,name=compile_status,json=compileStatus,proto3" json:"compile_status,omitempty"`
	ContestId            string   `protobuf:"bytes,8,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Kind                 string   `protobuf:"bytes,9,opt,name=kind,proto3" json:"kind,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	LanguageStatus       string   `protobuf:"bytes,11,opt,name=language_status,json=languageStatus,proto3" json:"language_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeResponse) Reset()         { *m = CodeResponse{} }
func (m *CodeResponse) String() string { return proto.CompactTextString(m) }
func (*CodeResponse) ProtoMessage()    {}
func (*CodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_291bbfa232056f92, []int{1}
}

func (m *CodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResponse.Unmarshal(m, b)
}
func (m *CodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResponse.Marshal(b, m, deterministic)
}
func (m *CodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResponse.Merge(m, src)
}
func (m *CodeResponse) XXX_Size() int {
	return xxx_messageInfo_CodeResponse.Size(m)
}
func (m *CodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResponse proto.InternalMessageInfo

func (m *CodeResponse) GetChallengeId() string {
	if m != nil {
		return m.ChallengeId
	}
	return ""
}

func (m *CodeResponse) GetChallengeSlug() string {
	if m != nil {
		return m.ChallengeSlug
	}
	return ""
}

func (m *CodeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CodeResponse) GetCodecheckerHash() string {
	if m != nil {
		return m.CodecheckerHash
	}
	return ""
}

func (m *CodeResponse) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *CodeResponse) GetCompileMessage() string {
	if m != nil {
		return m.CompileMessage
	}
	return ""
}

func (m *CodeResponse) GetCompileStatus() bool {
	if m != nil {
		return m.CompileStatus
	}
	return false
}

func (m *CodeResponse) GetContestId() string {
	if m != nil {
		return m.ContestId
	}
	return ""
}

func (m *CodeResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CodeResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CodeResponse) GetLanguageStatus() string {
	if m != nil {
		return m.LanguageStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*CodeRequest)(nil), "code.CodeRequest")
	proto.RegisterType((*CodeResponse)(nil), "code.CodeResponse")
}

func init() {
	proto.RegisterFile("services/code/service.proto", fileDescriptor_291bbfa232056f92)
}

var fileDescriptor_291bbfa232056f92 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0xdd, 0xed, 0x6e, 0x3b, 0x69, 0xb7, 0xe0, 0x93, 0xd5, 0x15, 0xd2, 0xd2, 0x15,
	0xda, 0xe5, 0x92, 0x20, 0xf6, 0x11, 0x7a, 0x69, 0x0f, 0x48, 0x28, 0x39, 0x70, 0x8c, 0x9c, 0xc4,
	0xc4, 0xa1, 0x6e, 0x1c, 0x6a, 0x07, 0xa9, 0x0f, 0xc0, 0xbb, 0xf2, 0x0a, 0xdc, 0x90, 0xc7, 0x76,
	0x09, 0x1c, 0x38, 0x71, 0xca, 0xf8, 0x9b, 0xdf, 0xe3, 0x7f, 0x26, 0x03, 0x77, 0x9a, 0x1f, 0xbf,
	0xb5, 0x15, 0xd7, 0x69, 0xa5, 0x6a, 0x9e, 0xfa, 0x53, 0xd2, 0x1f, 0x95, 0x51, 0xe4, 0xca, 0xb2,
	0xd5, 0x9d, 0x52, 0x5f, 0x54, 0x99, 0x22, 0x2a, 0x87, 0xcf, 0xa9, 0xe0, 0x4c, 0x1a, 0xe1, 0x24,
	0xeb, 0xef, 0x11, 0xc4, 0x1b, 0x55, 0xf3, 0x8c, 0x7f, 0x1d, 0xb8, 0x36, 0x84, 0x00, 0x5e, 0xa2,
	0xd1, 0x7d, 0xf4, 0x34, 0xcb, 0x30, 0x26, 0xaf, 0x61, 0x5e, 0xa9, 0xce, 0x70, 0x6d, 0x0a, 0x2d,
	0x87, 0x86, 0x5e, 0x60, 0x2e, 0xf6, 0x2c, 0x97, 0x43, 0x43, 0x56, 0x30, 0x95, 0xac, 0x6b, 0x06,
	0xd6, 0x70, 0x7a, 0x89, 0xe9, 0xf3, 0x99, 0x3c, 0xc0, 0xa2, 0x97, 0xec, 0x24, 0xdb, 0x70, 0xff,
	0x0a, 0x05, 0xf3, 0x00, 0x6d, 0x81, 0xf5, 0xcf, 0x0b, 0x98, 0x3b, 0x1f, 0xba, 0x57, 0x9d, 0x76,
	0x8f, 0x0a, 0x26, 0x25, 0xef, 0x1a, 0x5e, 0xb4, 0xb5, 0x37, 0x14, 0x9f, 0xd9, 0xae, 0x26, 0x6f,
	0xe0, 0xf6, 0xb7, 0x64, 0xe4, 0x6c, 0x71, 0xa6, 0xe8, 0x2d, 0xb4, 0x74, 0x39, 0x6a, 0xe9, 0x2d,
	0xbc, 0xb0, 0xdf, 0x4a, 0xf0, 0x6a, 0xcf, 0x8f, 0x85, 0x60, 0x5a, 0x78, 0x5b, 0xcb, 0x11, 0xdf,
	0x32, 0x2d, 0x08, 0x85, 0x9b, 0x4a, 0x1d, 0x7a, 0xd6, 0x9d, 0xe8, 0x04, 0x15, 0xe1, 0x48, 0x1e,
	0x61, 0x69, 0xc3, 0x56, 0xf2, 0xe2, 0xc0, 0xb5, 0xb6, 0xbd, 0x5f, 0xa3, 0xe2, 0xd6, 0xe3, 0x0f,
	0x8e, 0xa2, 0x51, 0x2f, 0xd4, 0x86, 0x99, 0x41, 0xd3, 0x9b, 0xfb, 0xe8, 0x69, 0x9a, 0x2d, 0x3c,
	0xcd, 0x11, 0x92, 0x57, 0x00, 0x61, 0xce, 0x6d, 0x4d, 0xa7, 0x58, 0x6a, 0xe6, 0xc9, 0xae, 0xb6,
	0x7d, 0xec, 0xdb, 0xae, 0xa6, 0x33, 0xd7, 0x87, 0x8d, 0xff, 0x98, 0x3b, 0xfc, 0x35, 0xf7, 0x47,
	0x58, 0x86, 0x38, 0x3c, 0x1b, 0x3b, 0x7b, 0x01, 0xbb, 0x77, 0xdf, 0xff, 0xf0, 0x3b, 0x90, 0xbb,
	0xe5, 0x21, 0xcf, 0x00, 0xf9, 0x50, 0x1e, 0x5a, 0x63, 0x21, 0x79, 0x99, 0xd8, 0x89, 0x24, 0xa3,
	0x25, 0x59, 0x91, 0x31, 0xf2, 0xff, 0xeb, 0x23, 0x4c, 0x36, 0x76, 0x6a, 0x64, 0x9d, 0xe0, 0xbe,
	0x25, 0x61, 0xdf, 0x92, 0x2d, 0xee, 0x1b, 0x26, 0x43, 0x81, 0x87, 0x7f, 0x6a, 0x7c, 0xc5, 0x0c,
	0x26, 0x9f, 0x98, 0xa9, 0xc4, 0x7f, 0xab, 0xf8, 0x2e, 0x2a, 0xaf, 0x31, 0xff, 0xfc, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0x90, 0x03, 0x4a, 0x37, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CodeServiceClient is the client API for CodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CodeServiceClient interface {
	SubmitCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error)
	Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error)
	Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (CodeService_WatchClient, error)
}

type codeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeServiceClient(cc grpc.ClientConnInterface) CodeServiceClient {
	return &codeServiceClient{cc}
}

func (c *codeServiceClient) SubmitCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*CodeResponse, error) {
	out := new(CodeResponse)
	err := c.cc.Invoke(ctx, "/code.CodeService/SubmitCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeServiceClient) Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error) {
	out := new(protobuf.HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/code.CodeService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeServiceClient) Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (CodeService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CodeService_serviceDesc.Streams[0], "/code.CodeService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &codeServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CodeService_WatchClient interface {
	Recv() (*protobuf.HealthCheckResponse, error)
	grpc.ClientStream
}

type codeServiceWatchClient struct {
	grpc.ClientStream
}

func (x *codeServiceWatchClient) Recv() (*protobuf.HealthCheckResponse, error) {
	m := new(protobuf.HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CodeServiceServer is the server API for CodeService service.
type CodeServiceServer interface {
	SubmitCode(context.Context, *CodeRequest) (*CodeResponse, error)
	Check(context.Context, *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error)
	Watch(*protobuf.HealthCheckRequest, CodeService_WatchServer) error
}

// UnimplementedCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCodeServiceServer struct {
}

func (*UnimplementedCodeServiceServer) SubmitCode(ctx context.Context, req *CodeRequest) (*CodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitCode not implemented")
}
func (*UnimplementedCodeServiceServer) Check(ctx context.Context, req *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedCodeServiceServer) Watch(req *protobuf.HealthCheckRequest, srv CodeService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterCodeServiceServer(s *grpc.Server, srv CodeServiceServer) {
	s.RegisterService(&_CodeService_serviceDesc, srv)
}

func _CodeService_SubmitCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServiceServer).SubmitCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/code.CodeService/SubmitCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServiceServer).SubmitCode(ctx, req.(*CodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/code.CodeService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServiceServer).Check(ctx, req.(*protobuf.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protobuf.HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeServiceServer).Watch(m, &codeServiceWatchServer{stream})
}

type CodeService_WatchServer interface {
	Send(*protobuf.HealthCheckResponse) error
	grpc.ServerStream
}

type codeServiceWatchServer struct {
	grpc.ServerStream
}

func (x *codeServiceWatchServer) Send(m *protobuf.HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "code.CodeService",
	HandlerType: (*CodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCode",
			Handler:    _CodeService_SubmitCode_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _CodeService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _CodeService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/code/service.proto",
}
